version: '3.8'
services:
  redis:
    image: redis:7-alpine
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - thudbot-network
    deploy:
      restart_policy:
        condition: any

  backend:
    image: bq31/thudbot-backend:latest  # Use Docker Hub image
    ports:
      - "8000:8000"
    secrets:
      - openai_api_key
      - langchain_api_key
    environment:
      - COMPOSE_MODE=true
      - ENV=prod
    networks:
      - thudbot-network
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 60s

secrets:
  openai_api_key:
    external: true
  langchain_api_key:
    external: true

networks:
  thudbot-network:
    driver: overlay
