# Docker Compose for Thudbot Development

services:
  redis:
    image: redis:7-alpine
    container_name: thudbot-redis
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - thudbot-network

  backend:
    build: 
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: thudbot-backend
    ports:
      - "8000:8000"
    environment:
      - COMPOSE_MODE=true
    env_file:
      - ../.env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - thudbot-network
    restart: unless-stopped

networks:
  thudbot-network:
    driver: bridge
